"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "es" | "en";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
    es: {
        footerDescription: "NocturneScope es la tesis para el título de Ingeniero de Ejecución en Computación e Informática que busca formalizar una plataforma para la gestión de redes.",
        socialNetworks: "Redes Sociales",
        madeBy: "Hecho por",
        copyright: "Copyright ©",
        logoAltLight: "Logo claro",
        logoAltDark: "Logo oscuro",
        // Navbar
        dashboard: "Dashboard",
        topology: "Topología",
        features: "Características",
        demo: "Demo",
        downloads: "Descarga",
        notifications: "Notificaciones",
        markAllRead: "Marcar todas como leídas",
        clearHistory: "Borrar historial",
        noNotifications: "No hay notificaciones",
        login: "Iniciar Sesión",
        goToDashboard: "Ir al Dashboard",
        myAccount: "Mi Cuenta",
        apiTokens: "Tokens API",
        adminAccount: "Administrar Cuenta",
        adminUsers: "Administrar Usuarios",
        logout: "Cerrar Sesión",
        changeGroup: "Cambiar Grupo",
        manageGroups: "Gestionar Grupos",
        // Dashboard
        device: "Dispositivo",
        metric: "Métrica",
        timeRange: "Rango de Tiempo",
        noDevices: "Sin dispositivos",
        status: "Estado",
        systemUnknown: "Sistema Desconocido",
        network: "Red",
        storage: "Almacenamiento",
        temperature: "Temperatura",
        coreTemp: "Core Temp",
        networkTraffic: "Tráfico de Red",
        download: "Descarga",
        upload: "Subida",
        used: "Usado",
        total: "Total",
        cores: "Núcleos",
        currentUsage: "Uso actual",
        partitionDetails: "Detalle de Particiones",
        timeParams: "Tiempos mostrados en",
        loading: "Cargando Dashboard...",
        noData: "Sin datos en el rango seleccionado",
        lastPoint: "Último punto",
        // Metrics
        cpu: "CPU (%)",
        ram: "RAM (%)",
        disk: "DISK (%)",
        net_rx: "Net RX (B/s)",
        net_tx: "Net TX (B/s)",
        temp: "Temp (°C)",
        // Landing
        heroTitle: "Bienvenido a NocturneScope",
        heroDescription: "NocturneScope es una plataforma de monitoreo y análisis de redes diseñada para automatizar tareas de seguridad y facilitar la gestión de infraestructuras de red.",
        githubRepo: "Repositorio Github",
        featureRealTime: "Monitoreo en Tiempo Real",
        featureRealTimeDesc: "Visualiza el tráfico de red y métricas de rendimiento en vivo para una toma de decisiones instantánea.",
        featureTopology: "Topología de Red",
        featureTopologyDesc: "Mapa interactivo que descubre y visualiza automáticamente la estructura y conexiones de tu red.",
        featureAlerts: "Alertas Inteligentes",
        featureAlertsDesc: "Sistema de detección de anomalías que te notifica sobre comportamientos sospechosos o fallos.",
        featureMultiPlatform: "Multi-Plataforma",
        featureMultiPlatformDesc: "Agentes ligeros y eficientes compatibles con sistemas Linux y Windows para una cobertura total.",
        featuresConclusion: "NocturneScope transforma la manera en que gestionas la seguridad de tu red. Nuestra plataforma unifica el monitoreo en tiempo real, la visualización avanzada de topologías y un sistema de alertas proactivo en una sola interfaz intuitiva. Diseñada para escalar con tu infraestructura, ofrece la visibilidad profunda y el control que necesitas para identificar vulnerabilidades, optimizar el rendimiento y responder a incidentes con velocidad y precisión, sin importar la complejidad de tu entorno.",
        videoComingSoon: "Video demostrativo próximamente",
        downloadsTitle: "Descarga el Agente",
        downloadsDesc: "Para comenzar a monitorear tus dispositivos, descarga y ejecuta el agente de NocturneScope en tus máquinas.",
        linuxDesc: "Compatible con la mayoría de distribuciones Linux modernas (Ubuntu, Debian, CentOS, etc).",
        downloadLinux: "Descargar para Linux",
        windowsDesc: "Ejecutable portable para Windows 10/11 y Server.",
        downloadWindows: "Descargar para Windows",
        // Auth
        loginTitle: "Iniciar sesión",
        loginSubtitle: "Accede a tu panel y administra tu red.",
        email: "Email",
        password: "Contraseña",
        username: "Usuario",
        loginBtn: "Entrar",
        loggingIn: "Entrando...",
        loginError: "Credenciales inválidas o backend no disponible.",
        noAccount: "¿No tienes cuenta?",
        createAccount: "Crear cuenta",
        registerTitle: "Crear cuenta",
        registerSubtitle: "Regístrate para usar el panel de NocturneScope.",
        registerBtn: "Registrarme",
        registerError: "No se pudo crear la cuenta (email/usuario en uso o backend caído).",
        registerSuccess: "Cuenta creada. Redirigiendo a login…",
        hasAccount: "Ya tengo cuenta",
        // Account Page
        profileInfo: "Información de Perfil",
        accountSubtitle: "Administra tu perfil y recursos asociados",
        group: "Grupo",
        actions: "Acciones",
        createdAt: "Creado",
        editProfile: "Editar Perfil",
        role: "Rol",
        saveChanges: "Guardar Cambios",
        newPassword: "Nueva Contraseña",
        confirmPassword: "Confirmar Contraseña",
        passwordMismatch: "Las contraseñas no coinciden",
        profileUpdated: "Perfil actualizado correctamente",
        errorProfileUpdate: "Error actualizando perfil",
        confirmRevoke: "¿Estás seguro? Esto revocará el token y desconectará el agente.",
        // LogViewer
        errorLoadingLogs: "Error cargando logs",
        systemLogs: "Logs del Sistema",
        paused: "Pausado",
        live: "En vivo",
        time: "Tiempo",
        noRecentData: "Sin datos recientes",
        page: "Página",
        of: "de",
        previous: "Anterior",
        next: "Siguiente",
        // Admin Users
        userManagement: "Gestión de Usuarios",
        manageUsersDesc: "Administra todos los usuarios del sistema",
        createUser: "Crear Usuario",
        confirmDeleteUser: "Confirmar Eliminación",
        deleteUserMsg: "¿Estás seguro de que deseas eliminar al usuario",
        failedLoadUsers: "Error al cargar usuarios",
        id: "ID",
        name: "Nombre",
        description: "Descripción",
        noDescription: "Sin descripción",
        noUsersFound: "No se encontraron usuarios",
        editUser: "Editar Usuario",
        deleteUserTitle: "Eliminar Usuario",
        createNewUser: "Crear Nuevo Usuario",
        passwordRequired: "La contraseña es obligatoria para nuevos usuarios",
        leaveBlank: "dejar en blanco para mantener la actual",
        saving: "Guardando...",
        create: "Crear",
        update: "Actualizar",
        save: "Guardar",
        editGroup: "Editar Grupo",
        deleteGroupTitle: "Eliminar Grupo",
        groupNamePlaceholder: "Ej: Servidores Producción",
        groupDescPlaceholder: "Descripción opcional del grupo...",
        errorOccurred: "Ocurrió un error",
        // Tokens Page
        tokenManagement: "Gestión de Tokens API",
        tokenManagementDesc: "Administra los tokens de acceso para tus dispositivos",
        createToken: "Crear Token",
        tokenName: "Nombre del Token",
        tokenCreated: "Token Creado",
        tokenCreatedDesc: "Guarda este token en un lugar seguro. No podrás verlo nuevamente.",
        copy: "Copiar",
        copySuccess: "Token copiado al portapapeles",
        close: "Cerrar",
        detectedDevices: "Dispositivos Detectados",
        detectedDevicesDesc: "Equipos que han enviado métricas recientemente. Crea un token para gestionarlos.",
        noDevicesDetected: "No se han detectado dispositivos aún.",
        managed: "Gestionado",
        unassigned: "Sin Asignar",
        active: "Activo",
        inactive: "Inactivo",
        infoTitle: "Información",
        infoToken1: "Cada token está asociado a un dispositivo y un grupo específico",
        infoToken2: "Los tokens permiten que tus dispositivos envíen métricas al sistema",
        infoToken3: "Guarda el token en un lugar seguro, solo se muestra una vez al crearlo",
        infoToken4: "Puedes eliminar tokens que ya no uses",
        confirmDeleteToken: "¿Estás seguro de eliminar este token? Esta acción no se puede deshacer.",
        confirmDeleteDevice: "¿Estás seguro de eliminar el dispositivo",
        devicePlaceholder: "Ej: servidor-linux-01",
        deviceHint: "Escribe el nombre del nuevo dispositivo o selecciona uno existente. Si se deja vacío, se actualizará automáticamente al conectar el agente.",
        // Groups Page
        myGroups: "Mis Grupos",
        selectGroupDesc: "Selecciona un grupo para ver sus dispositivos",
        newGroup: "Nuevo Grupo",
        noGroups: "No tienes grupos creados",
        createFirstGroup: "Crea tu primer grupo para comenzar a monitorear dispositivos",
        createGroupBtn: "Crear mi primer grupo",
        groupCreated: "Grupo creado exitosamente",
        groupUpdated: "Grupo actualizado exitosamente",
        groupDeleted: "Grupo eliminado exitosamente",
        confirmDeleteGroup: "¿Estás seguro de eliminar el grupo",
        // Topology - Controls
        topologyControls: "Controles de Topología",
        tools: "Herramientas",
        catAll: "Todos",
        catMonitoring: "Monitoreo",
        catTriggers: "Disparadores",
        catLogic: "Lógica",
        catActions: "Acciones",
        // Topology - Tooltips & Labels
        metricChart: "Gráfico",
        metricChartDesc: "Visualiza métricas en tiempo real (CPU, RAM, etc.) de un dispositivo conectado.",
        detailsNode: "Detalles",
        detailsNodeDesc: "Muestra información detallada (OS, IP, Estado) del dispositivo conectado en el canvas.",
        trafficNode: "Tráfico",
        trafficNodeDesc: "Monitorea el tráfico de red entrante y saliente del dispositivo.",
        statsNode: "Estadística",
        statsNodeDesc: "Muestra una tarjeta de estadística específica (CPU, RAM, etc.) para un dispositivo.",
        actionNode: "Acción",
        actionNodeDesc: "Evalúa una condición sobre una métrica (ej: CPU > 80%) para disparar alertas.",
        trafficTrigger: "Trigger",
        trafficTriggerDesc: "Dispara alertas basadas en patrones de tráfico específicos (ej: puerto, protocolo).",
        delayNode: "Delay",
        delayNodeDesc: "Introduce una pausa configurable antes de pasar la señal al siguiente nodo.",
        windowNode: "Ventana",
        windowNodeDesc: "Permite el paso de señales solo dentro de un horario específico configurado.",
        thresholdNode: "Umbral",
        thresholdNodeDesc: "Requiere que una señal se repita X veces en un tiempo dado antes de activarse.",
        emailNode: "Email",
        emailNodeDesc: "Envía un correo electrónico de alerta cuando recibe una señal de activación.",
        notificationNode: "Notificación",
        notificationNodeDesc: "Muestra una notificación emergente (toast) en la pantalla del usuario.",
        soundNode: "Sonido",
        soundNodeDesc: "Reproduce un sonido de alarma cuando se activa.",
        // Topology - Config
        configTitle: "Configuración de",
        ruleType: "Tipo de Regla",
        value: "Valor",
        threatLevel: "Nivel de Amenaza",
        port: "Puerto",
        protocol: "Protocolo",
        ipAddr: "Dirección IP",
        changeDevice: "Cambiar Dispositivo",
        nodeColor: "Color del Nodo",
        monitoredDevice: "Dispositivo Monitorizado",
        metricType: "Tipo de Métrica",
        selectDevice: "Seleccionar dispositivo...",
        selectMetric: "Seleccionar métrica...",
        operator: "Operador",
        thresholdAttempt: "Umbral (Intentos)",
        recipient: "Destinatario (To)",
        subject: "Asunto",
        content: "Contenido",
        testSend: "Probar Envío",
        testSendSuccess: "Correo de prueba enviado a",
        testSendError: "Error enviando correo",
        enterRecipient: "Por favor ingresa un destinatario primero.",
        message: "Mensaje",
        delayMs: "Retraso (ms)",
        delayHint: "1000ms = 1 segundo",
        soundType: "Tipo de Sonido",
        startTime: "Hora Inicio (HH:mm)",
        endTime: "Hora Fin (HH:mm)",
        timeWindowSec: "Ventana de Tiempo (segundos)",
        currentState: "Estado actual",
        connected: "Conectado",
        disconnected: "Desconectado",
        // Topology - Misc
        availableDevices: "Disponibles",
        noAvailableDevices: "No hay dispositivos",
        dragToAdd: "Arrastra para agregar",
        savedTopologies: "Topologías Guardadas",
        selectTopology: "Seleccionar topología...",
        newTopology: "Nueva Topología",
        saveTopology: "Guardar",
        saveTopologyTitle: "Guardar Topología",
        topologyNamePlaceholder: "Nombre de la topología",
        renameTopologyTitle: "Renombrar Topología",
        rename: "Renombrar",
        deleteTopologyTitle: "Eliminar Topología",
        deleteConfirmMsg: "¿Estás seguro de que deseas eliminar esta topología? Esta acción no se puede deshacer.",
        delete: "Eliminar",
        cancel: "Cancelar",
        confirm: "Confirmar",
        devices: "Dispositivos",
        connectedTo: "Conectado a",
        notConnected: "No conectado a ningún dispositivo",
        // Time Ranges
        t_30m: "30 Minutos",
        t_1h: "1 Hora",
        t_6h: "6 Horas",
        t_24h: "24 Horas",
        t_7d: "7 Días",
        // Topology - Device Details
        lastActivity: "Última Actividad",
        resources: "Recursos",
        loadingDetails: "Cargando detalles...",
        errorDetails: "Error al cargar datos del dispositivo",
        unknown: "Desconocido",
        never: "Nunca",
        os: "Sistema Operativo",
        noDataAvailable: "No hay datos disponibles",
        online: "En línea",
        offline: "Desconectado",
        gateway: "Gateway",
        cpuSimple: "CPU",
        ramSimple: "RAM",
        netRxSimple: "Net RX",
        netTxSimple: "Net TX",
        viewDashboard: "Ver Dashboard",
        selectDeviceFromTopology: "Seleccionar dispositivo...",
        // Reports
        reports: "Reportes",
        reportGeneration: "Generación de Reportes",
        reportGenerationDesc: "Crea y exporta reportes detallados de rendimiento para tus dispositivos.",
        reportScope: "Alcance del Reporte",
        singleDevice: "Dispositivo Único",
        groupSummary: "Resumen de Grupo",
        generatingFor: "Generando reporte para",
        devicesInGroup: "dispositivos en el grupo",
        criticalThresholds: "Umbrales Críticos",
        criticalCpu: "CPU Crítico (%)",
        criticalRam: "RAM Crítica (%)",
        criticalTemp: "Temperatura Crítica (°C)",
        generateReport: "Generar Reporte",
        generating: "Generando...",
        selectDeviceFirst: "Selecciona un dispositivo primero",
        noDevicesGroup: "No hay dispositivos en este grupo",
        reportReady: "Reporte Listo",
        generatedFor: "Generado para",
        showPreview: "Mostrar Vista Previa",
        hidePreview: "Ocultar Vista Previa",
        processing: "Procesando...",
        generatedAt: "Generado en",
        totalDevices: "Total Dispositivos",
        clickPreview: "Haz clic en 'Mostrar Vista Previa' para ver el PDF aquí, o 'Descargar' para guardarlo.",
        noReport: "Sin Reporte Generado",
        configureReport: "Configura los ajustes y haz clic en 'Generar Reporte' para ver los resultados aquí.",
        selectMetrics: "Métricas a Incluir",
        // PDF Report Labels
        criticalTempMsg: "Temperatura promedio excede umbral",
        dataTablesSection: "Tablas de Datos",

        groupHealthReport: "Reporte de Salud del Grupo",
        systemPerformanceReport: "Reporte de Rendimiento del Sistema",
        executiveSummary: "Resumen Ejecutivo",
        topOffenders: "Top Consumo",
        topOffendersDesc: "Dispositivos con mayor consumo de recursos o alertas.",
        criticalEventsAnalysis: "Análisis de Eventos Críticos",
        criticalEventsDesc: "Eventos donde el uso excedió los umbrales definidos.",
        detailedStatistics: "Estadísticas Detalladas",
        groupAverages: "Promedios de Grupo",
        average: "Promedio",
        alerts: "Alertas",
        cpuUsage: "Uso de CPU (%)",
        ramUsage: "Uso de RAM (%)",
        // temp: "Temperatura (°C)", // Already likely exists or covered by metric
        netRx: "Red Recibido (B/s)",
        netTx: "Red Enviado (B/s)",
        groupTrends: "Tendencias Promedio del Grupo",
        deviceHealthDist: "Distribución de Salud",
        axisTime: "Tiempo",
        axisValue: "Valor",
        noCriticalEvents: "No se detectaron eventos críticos en este rango.",
        moreEventsOmitted: "más eventos omitidos",
        // New Ranges
        t_30d: "30 Días",
        t_5m: "5 Meses",
        t_1y: "1 Año",

    },
    en: {
        footerDescription: "NocturneScope is the thesis for the Computer Execution Engineer degree seeking to formalize a platform for network management.",
        socialNetworks: "Social Networks",
        madeBy: "Made by",
        copyright: "Copyright ©",
        logoAltLight: "Light Logo",
        logoAltDark: "Dark Logo",
        // Navbar
        dashboard: "Dashboard",
        topology: "Topology",
        features: "Features",
        demo: "Demo",
        downloads: "Download",
        notifications: "Notifications",
        markAllRead: "Mark all as read",
        clearHistory: "Clear history",
        noNotifications: "No notifications",
        login: "Login",
        goToDashboard: "Go to Dashboard",
        myAccount: "My Account",
        apiTokens: "API Tokens",
        adminAccount: "Manage Account",
        adminUsers: "Manage Users",
        logout: "Logout",
        changeGroup: "Change Group",
        manageGroups: "Manage Groups",
        // Dashboard
        device: "Device",
        metric: "Metric",
        timeRange: "Time Range",
        noDevices: "No devices",
        status: "Status",
        systemUnknown: "Unknown System",
        network: "Network",
        storage: "Storage",
        temperature: "Temperature",
        coreTemp: "Core Temp",
        networkTraffic: "Network Traffic",
        download: "Download",
        upload: "Upload",
        used: "Used",
        total: "Total",
        cores: "Cores",
        currentUsage: "Current Usage",
        partitionDetails: "Partition Details",
        timeParams: "Times shown in",
        loading: "Loading Dashboard...",
        noData: "No data in selected range",
        lastPoint: "Last point",
        // Metrics
        cpu: "CPU (%)",
        ram: "RAM (%)",
        disk: "DISK (%)",
        net_rx: "Net RX (B/s)",
        net_tx: "Net TX (B/s)",
        temp: "Temp (°C)",
        // Landing
        heroTitle: "Welcome to NocturneScope",
        heroDescription: "NocturneScope is a network monitoring and analysis platform designed to automate security tasks and facilitate network infrastructure management.",
        githubRepo: "Github Repository",
        featureRealTime: "Real-Time Monitoring",
        featureRealTimeDesc: "Visualize network traffic and performance metrics live for instant decision making.",
        featureTopology: "Network Topology",
        featureTopologyDesc: "Interactive map that automatically discovers and visualizes your network structure and connections.",
        featureAlerts: "Smart Alerts",
        featureAlertsDesc: "Anomaly detection system that notifies you of suspicious behavior or failures.",
        featureMultiPlatform: "Multi-Platform",
        featureMultiPlatformDesc: "Lightweight and efficient agents compatible with Linux and Windows systems for total coverage.",
        featuresConclusion: "NocturneScope transforms the way you manage your network security. Our platform unifies real-time monitoring, advanced topology visualization, and a proactive alert system in a single intuitive interface. Designed to scale with your infrastructure, it offers the deep visibility and control you need to identify vulnerabilities, optimize performance, and respond to incidents with speed and precision, regardless of your environment's complexity.",
        videoComingSoon: "Demo video coming soon",
        downloadsTitle: "Download Agent",
        downloadsDesc: "To start monitoring your devices, download and run the NocturneScope agent on your machines.",
        linuxDesc: "Compatible with most modern Linux distributions (Ubuntu, Debian, CentOS, etc).",
        downloadLinux: "Download for Linux",
        windowsDesc: "Portable executable for Windows 10/11 and Server.",
        downloadWindows: "Download for Windows",
        // Auth
        loginTitle: "Login",
        loginSubtitle: "Access your dashboard and manage your network.",
        email: "Email",
        password: "Password",
        username: "Username",
        loginBtn: "Login",
        loggingIn: "Logging in...",
        loginError: "Invalid credentials or backend unavailable.",
        noAccount: "Don't have an account?",
        createAccount: "Create account",
        registerTitle: "Create account",
        registerSubtitle: "Register to use the NocturneScope panel.",
        registerBtn: "Sign up",
        registerError: "Could not create account (email/username in use or backend down).",
        registerSuccess: "Account created. Redirecting to login...",
        hasAccount: "Already have an account?",
        // Account Page
        profileInfo: "Profile Information",
        accountSubtitle: "Manage your profile and associated resources",
        group: "Group",
        actions: "Actions",
        createdAt: "Created",
        editProfile: "Edit Profile",
        role: "Role",
        saveChanges: "Save Changes",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        passwordMismatch: "Passwords do not match",
        profileUpdated: "Profile updated successfully",
        errorProfileUpdate: "Error updating profile",
        confirmRevoke: "Are you sure? This will revoke the token and disconnect the agent.",
        // LogViewer
        errorLoadingLogs: "Error loading logs",
        systemLogs: "System Logs",
        paused: "Paused",
        live: "Live",
        time: "Time",
        noRecentData: "No recent data",
        page: "Page",
        of: "of",
        previous: "Previous",
        next: "Next",
        // Admin Users
        userManagement: "User Management",
        manageUsersDesc: "Manage all users in the system",
        createUser: "Create User",
        confirmDeleteUser: "Confirm Delete",
        deleteUserMsg: "Are you sure you want to delete user",
        failedLoadUsers: "Failed to load users",
        id: "ID",
        name: "Name",
        description: "Description",
        noDescription: "No description",
        noUsersFound: "No users found",
        editUser: "Edit User",
        deleteUserTitle: "Delete User",
        createNewUser: "Create New User",
        passwordRequired: "Password is required for new users",
        leaveBlank: "leave blank to keep current",
        saving: "Saving...",
        create: "Create",
        update: "Update",
        save: "Save",
        editGroup: "Edit Group",
        deleteGroupTitle: "Delete Group",
        groupNamePlaceholder: "Ex: Production Servers",
        groupDescPlaceholder: "Optional group description...",
        errorOccurred: "An error occurred",
        // Tokens Page
        tokenManagement: "API Token Management",
        tokenManagementDesc: "Manage access tokens for your devices",
        createToken: "Create Token",
        tokenName: "Token Name",
        tokenCreated: "Token Created",
        tokenCreatedDesc: "Save this token in a safe place. You won't be able to see it again.",
        copy: "Copy",
        copySuccess: "Token copied to clipboard",
        close: "Close",
        detectedDevices: "Detected Devices",
        detectedDevicesDesc: "Equipment that has sent metrics recently. Create a token to manage them.",
        noDevicesDetected: "No devices detected yet.",
        managed: "Managed",
        unassigned: "Unassigned",
        active: "Active",
        inactive: "Inactive",
        infoTitle: "Information",
        infoToken1: "Each token is associated with a specific device and group",
        infoToken2: "Tokens allow your devices to send metrics to the system",
        infoToken3: "Keep the token safe, it is only shown once upon creation",
        infoToken4: "You can delete tokens you no longer use",
        confirmDeleteToken: "Are you sure you want to delete this token? This action cannot be undone.",
        confirmDeleteDevice: "Are you sure you want to delete device",
        devicePlaceholder: "Ex: linux-server-01",
        deviceHint: "Type the name of the new device or select an existing one. If left empty, it will update automatically when the agent connects.",
        // Groups Page
        myGroups: "My Groups",
        selectGroupDesc: "Select a group to see its devices",
        newGroup: "New Group",
        noGroups: "You have no groups created",
        createFirstGroup: "Create your first group to start monitoring devices",
        createGroupBtn: "Create my first group",
        groupCreated: "Group created successfully",
        groupUpdated: "Group updated successfully",
        groupDeleted: "Group deleted successfully",
        confirmDeleteGroup: "Are you sure you want to delete group",
        // Topology - Controls
        topologyControls: "Topology Controls",
        tools: "Tools",
        catAll: "All",
        catMonitoring: "Monitoring",
        catTriggers: "Triggers",
        catLogic: "Logic",
        catActions: "Actions",
        // Topology - Tooltips & Labels
        metricChart: "Chart",
        metricChartDesc: "Visualize real-time metrics (CPU, RAM, etc.) from a connected device.",
        detailsNode: "Details",
        detailsNodeDesc: "Show detailed information (OS, IP, Status) of the connected device on the canvas.",
        trafficNode: "Traffic",
        trafficNodeDesc: "Monitor incoming and outgoing network traffic of the device.",
        statsNode: "Statistic",
        statsNodeDesc: "Show a specific statistic card (CPU, RAM, etc.) for a device.",
        actionNode: "Action",
        actionNodeDesc: "Evaluate a condition on a metric (e.g., CPU > 80%) to trigger alerts.",
        trafficTrigger: "Trigger",
        trafficTriggerDesc: "Trigger alerts based on specific traffic patterns (e.g., port, protocol).",
        delayNode: "Delay",
        delayNodeDesc: "Introduce a configurable pause before passing the signal to the next node.",
        windowNode: "Window",
        windowNodeDesc: "Allow signal passage only within a configured specific time schedule.",
        thresholdNode: "Threshold",
        thresholdNodeDesc: "Require a signal to repeat X times within a given time before activating.",
        emailNode: "Email",
        emailNodeDesc: "Send an alert email when an activation signal is received.",
        notificationNode: "Notification",
        notificationNodeDesc: "Show a popup notification (toast) on the user screen.",
        soundNode: "Sound",
        soundNodeDesc: "Play an alarm sound when activated.",
        // Topology - Config
        configTitle: "Configuration of",
        ruleType: "Rule Type",
        value: "Value",
        threatLevel: "Threat Level",
        port: "Port",
        protocol: "Protocol",
        ipAddr: "IP Address",
        changeDevice: "Change Device",
        nodeColor: "Node Color",
        monitoredDevice: "Monitored Device",
        metricType: "Metric Type",
        selectDevice: "Select device...",
        selectMetric: "Select metric...",
        operator: "Operator",
        thresholdAttempt: "Threshold (Attempts)",
        recipient: "Recipient (To)",
        subject: "Subject",
        content: "Content",
        testSend: "Test Send",
        testSendSuccess: "Test email sent to",
        testSendError: "Error sending email",
        enterRecipient: "Please enter a recipient first.",
        message: "Message",
        delayMs: "Delay (ms)",
        delayHint: "1000ms = 1 second",
        soundType: "Sound Type",
        startTime: "Start Time (HH:mm)",
        endTime: "End Time (HH:mm)",
        timeWindowSec: "Time Window (seconds)",
        currentState: "Current state",
        connected: "Connected",
        disconnected: "Disconnected",
        // Topology - Misc
        availableDevices: "Available",
        noAvailableDevices: "No devices",
        dragToAdd: "Drag to add",
        savedTopologies: "Saved Topologies",
        selectTopology: "Select topology...",
        newTopology: "New Topology",
        saveTopology: "Save",
        saveTopologyTitle: "Save Topology",
        topologyNamePlaceholder: "Topology Name",
        renameTopologyTitle: "Rename Topology",
        rename: "Rename",
        deleteTopologyTitle: "Delete Topology",
        deleteConfirmMsg: "Are you sure you want to delete this topology? This action cannot be undone.",
        delete: "Delete",
        cancel: "Cancel",
        confirm: "Confirm",
        devices: "Devices",
        connectedTo: "Connected to",
        notConnected: "Not connected to any device",
        // Time Ranges
        t_30m: "30 Minutes",
        t_1h: "1 Hour",
        t_6h: "6 Hours",
        t_24h: "24 Hours",
        t_7d: "7 Days",
        // Topology - Device Details
        lastActivity: "Last Activity",
        resources: "Resources",
        loadingDetails: "Loading details...",
        errorDetails: "Error loading device data",
        unknown: "Unknown",
        never: "Never",
        os: "Operating System",
        noDataAvailable: "No data available",
        online: "Online",
        offline: "Offline",
        gateway: "Gateway",
        cpuSimple: "CPU",
        ramSimple: "RAM",
        netRxSimple: "Net RX",
        netTxSimple: "Net TX",
        viewDashboard: "View Dashboard",
        selectDeviceFromTopology: "Select device...",
        // Reports
        reports: "Reports",
        reportGeneration: "Report Generation",
        reportGenerationDesc: "Create and export detailed performance reports for your devices.",
        reportScope: "Report Scope",
        singleDevice: "Single Device",
        groupSummary: "Group Summary",
        generatingFor: "Generating report for",
        devicesInGroup: "devices in group",
        criticalThresholds: "Critical Thresholds",
        criticalCpu: "Critical CPU (%)",
        criticalRam: "Critical RAM (%)",
        generateReport: "Generate Report",
        generating: "Generating...",
        selectDeviceFirst: "Select a device first",
        noDevicesGroup: "No devices in this group",
        reportReady: "Report Ready",
        generatedFor: "Generated for",
        showPreview: "Show Preview",
        hidePreview: "Hide Preview",
        processing: "Processing...",
        generatedAt: "Generated At",
        totalDevices: "Total Devices",
        clickPreview: "Click 'Show Preview' to view the PDF here, or 'Download' to save it.",
        noReport: "No Report Generated",
        configureReport: "Configure settings and click 'Generate Report' to see results here.",
        selectMetrics: "Metrics to Include",
        // PDF Report Labels
        criticalTemp: "Avg Temperature exceeds threshold",
        dataTablesSection: "Data Tables",
        groupHealthReport: "Group Health Report",
        systemPerformanceReport: "System Performance Report",
        executiveSummary: "Executive Summary",
        topOffenders: "Top Offenders",
        topOffendersDesc: "High consumption devices or alerts.",
        criticalEventsAnalysis: "Critical Events Analysis",
        criticalEventsDesc: "Events where usage exceeded defined thresholds.",
        detailedStatistics: "Detailed Statistics",
        groupAverages: "Group Averages",
        average: "Average",
        alerts: "Alerts",
        cpuUsage: "CPU Usage (%)",
        ramUsage: "RAM Usage (%)",
        netRx: "Network RX (B/s)",
        netTx: "Network TX (B/s)",
        groupTrends: "Group Average Trends",
        deviceHealthDist: "Device Health Distribution",
        axisTime: "Time",
        axisValue: "Value",
        noCriticalEvents: "No critical events detected in this range.",
        moreEventsOmitted: "more events omitted",
        // New Ranges
        t_30d: "30 Days",
        t_5m: "5 Months",
        t_1y: "1 Year",

    },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>("es");

    useEffect(() => {
        const savedLanguage = localStorage.getItem("language") as Language;
        if (savedLanguage) {
            setLanguage(savedLanguage);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("language", lang);
    };

    const t = (key: string) => {
        // @ts-ignore
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
